apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service-portfolio-api-tls
  namespace: service-portfolio
  labels:
    app: service-portfolio-api
    environment: production
spec:
  secretName: service-portfolio-api-tls
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - serviceportfolioapi.pablohgdev.com
  duration: 2160h
  renewBefore: 720h
