apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: service-portfolio-api
  namespace: service-portfolio
  labels:
    app: service-portfolio-api
    environment: production
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`serviceportfolioapi.pablohgdev.com`)
      kind: Rule
      services:
        - name: service-portfolio-api
          port: 8080
      middlewares:
        - name: security-headers
  tls:
    secretName: service-portfolio-api-tls
