spring:
  application:
    name: service-portfolio
  # --- Spring AI ---
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1
          temperature: 0.2
          max-tokens: 8192