apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: service-portfolio
  labels:
    app: service-portfolio-api
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"
      Server: ""
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    frameDeny: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: service-portfolio-api-dev
  namespace: service-portfolio
  labels:
    app: service-portfolio-api-dev
    environment: development
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`serviceportfolioapi-dev.pablohgdev.com`)
      kind: Rule
      services:
        - name: service-portfolio-api-dev
          port: 8080
      middlewares:
        - name: security-headers
  tls:
    secretName: service-portfolio-api-dev-tls
