apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-portfolio-api-dev
  namespace: service-portfolio
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-clusterissuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: serviceportfolioapi-dev.pablohgdev.com
      http:
        paths:
          - backend:
              service:
                name: service-portfolio-api-dev
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - serviceportfolioapi-dev.pablohgdev.com
      secretName: service-portfolio-api-dev-tls
