apiVersion: v1
kind: Service
metadata:
  name: service-portfolio-api
  namespace: service-portfolio
spec:
  selector:
    app: service-portfolio-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
